# ./docker-compose.yml

version: '3'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: test_db
      MARIADB_USER: test_user 
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - db
    ports:
      - "8000:3030"
    stdin_open: true
    tty: true
