LOAD DATA LOCAL INFILE './User.dat' 
INTO TABLE User
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, UserFName, UserMName, UserLName);

LOAD DATA LOCAL INFILE './Patron.dat' 
INTO TABLE Patron
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID);

LOAD DATA LOCAL INFILE './Staff.dat' 
INTO TABLE Staff
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID);

LOAD DATA LOCAL INFILE './Book.dat' 
INTO TABLE Book
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(BookID, BookTitle, Author, Genre, LocationID, ISBN);

LOAD DATA LOCAL INFILE './Fines.dat'
INTO TABLE Fines
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, BookID, FineID, Amount);

LOAD DATA LOCAL INFILE './Checkouts.dat'
INTO TABLE Checkouts
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, BookID, CheckOutID, CheckedOutDate, DueDate, ReturnedDate);
