LOAD DATA INFILE './users.dat' 
INTO TABLE User
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, UserFName, UserMName, UserLName);

LOAD DATA INFILE './file.csv' 
INTO TABLE Patron
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID);

LOAD DATA INFILE './file.csv' 
INTO TABLE Staff
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID);

LOAD DATA INFILE './file.csv' 
INTO TABLE Book
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(BookID, BookTitle, Author, Genre, LocationID, ISBN);

LOAD DATA INFILE './file.csv'
INTO TABLE Fines
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, BookID, FineID, Amount);

LOAD DATA INFILE './file.csv'
INTO TABLE Checkouts
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
(UserLibraryID, BookID, CheckOutID, CheckedOutDate, DueDate, ReturnedDate);

